# Generated by Django 3.1 on 2020-12-31 08:37

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201222_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 4 to 20 characters.Beginning with an alphabet. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, django.core.validators.RegexValidator(message='Please make sure username is 4 to 20 characters long, starting with an alphabet.', regex='^[a-zA-Z].{3,19}\\Z')], verbose_name='Username'),
        ),
    ]
